version: '3'

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - nginx_network
    ports:
      - 5010:8080

  backend:
    build: ./back-end
    depends_on:
      - db
    networks:
      - db_network
      - nginx_network
  
  frontend:
    build: ./front-end
    networks:
      - nginx_network

  db:
    image: postgres:14-alpine
    volumes: 
      - db_volume:/var/lib/postgresql
    environment:
      - POSTGRES_DB=dontpanic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db_network

volumes:
  db_volume:
  
networks:
  db_network:
  nginx_network: