version: '3'

services:

  backend:
    build: ./back-end
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - db_network
      - front_network
  
  frontend:
    build: ./front-end
    depends_on:
      - backend
    ports: 
      - 8081:8081
    networks:
      - front_network

  db:
    image: postgres:14-alpine
    volumes: 
      - db_volume:/var/lib/postgresql
    environment:
      - POSTGRES_DB=dontpanic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - db_network

volumes:
  db_volume:
networks:
  db_network:
  front_network: